### PR TITLE
add key api call had two parameters for the project id

### PR DESCRIPTION
**Pull request by bdonald25**
#1989

### CODE REVIEW

**Comment by jaypoulz** [comment]
I think it might be best to make the second param silently do the right think, instead of removing it altogether. That is, if [:id] OR [:project_id] exist, grab one and perform the action:

2. unless [:id].nil? id_you_should_use = [:id] else [:project_id]

**Comment by bdonald25** [comment]
@jaypoulz id will always exist though as is in the url. Are you suggesting that I use :project_id as a default over :id?

Previously :id was in url and :project_id was passed as a param. :project_id was used and :id was never looked at.
Now :id is still there but is actually being used and :project_id is gone. 

Do you suggest that I use :project_id if it exists else use :id?

**Comment by jaypoulz** [comment]
I am suggesting the exact opposite of what you just said.
Default to [:id]

**Comment by bdonald25** [comment]
That does not fix the problem though.
before isenseproject.org/api/v1/projects/3/add_key?... contrib_key: { project_id: 2, ...} -> adds key to project 2.
now (same api call) isenseproject.org/api/v1/projects/3/add_key?... contrib_key: { project_id: 2, ...} -> adds key to project 3
If I default to :id that problem will still exist. :id still exists in both api calls.

**Comment by jaypoulz** [comment]
Yes. The correct behavior for isenseproject.org/api/v1/projects/3/add_key... contrib_key: { project_id: 2, ...} is to add a key to project 3.

My confusion was that i didn't realize that the url param 'id' MUST exist because it is in the url. You don't even have to add a check for project_id, just ignore it altogether.

**Comment by bdonald25** [comment]
@jaypoulz Yes I agree. That is why I asked if it should default to project_id so that it continues to post to 2.

**Comment by jaypoulz** [comment]
My argument is - but that's stupid.

You could add an error case for this call that checks if they're the same, and if they aren't, spit out an error.

This way, it might break the end-user's behavior, but it would tell them why.

OR

We could default to project_id even though that's just disgusting.

**Comment by jdalphon** [comment]
@bdonald25 You'll get your coffee if I am ever in the lab again. You are correct as to what it would do. @jaypoulz && @bdonald25 This is a pretty odd case. The solution to the problem depends on why add_key was added to the api in the first place. If an external user requested it then it needs a patch as Jeremy pointed out. If it was something that someone internal asked for, I would say this pull works. 

In any case, from now on I should be the only one reviewing API changes. I didnt look at the add_key (at least not well) and I will take the blame on that one. If you dont hear from me on a pull quickly just send me a hangouts message and ill get right on it.

**Comment by jaypoulz** [comment]
@jdalphon Y'okay :smile:

**Comment by bdonald25** [comment]
@jdalphon I was the one who wanted it. :)

**Pull request merged**
