### PR TITLE
Finishing touches on Slickgrid

### PR DESCRIPTION
**Pull request by asalani93**
1/2 of the PRs that address #1949 and #1938.  #1764 

* Changes column header for merged latitude and longitude fields from "Latitude & Longitude" to "Latitude, Longitude" to provide more information about how to correctly enter the data.
* Fixes tests that relied on the presence of the ampersand to assert validity of the something something something
* Upgrades version of better-datetimepicker to the one that doesn't restrict the user in to enter dates between December and February

This will fail testing until the other half of the PR is merged into better-datetimepicker.  I'm not sure if I'm allowed to merge my own PRs w/o review (that would defeat part of the purpose of migrating them to the isenseDev repos).

Don't merge until this passes testing.  There's one more commit I need to make (basically run bundle install and commit the Gemfile.lock).  The current Gemfile.lock refers to my local version of better-datetimepicker.

### CODE REVIEW

**Comment by kcarcia** [comment]
@asalani93 where's your other PR? Did you or someone else already merge it?

**Comment by asalani93** [comment]
It's on the better-datetimpicker repo.

**Comment by kcarcia** [comment]
@asalani93 I merged it and restarted tests for this PR. The code looks fine to me, but I won't able to pull this locally and test until tomorrow. I'm sure it'll be fine. Thanks for taking care of this on short notice!!!

**Comment by kcarcia** [comment]
@asalani93 Ok, so day classes are canceled tomorrow and I won't be there at night. So, I can test this early Friday. 

But if @jaypoulz or @JKinsman or @stowellm or anyone else is either set up at home or will be on campus tomorrow night, it'd be super awesome if you could test this locally please!

**Comment by kcarcia** [comment]
@asalani93 Thank you for your very quick work on this, Anthony. I will test locally tomorrow morning.

**Comment by jaypoulz** [comment]
@kcarcia I'll take this review. I'll be in early tomorrow morning, assuming campus is open. Otherwise, I'll test it anyway, just from home. I'll be on gchat/hangouts all day if anyone needs to talk to me. :smile:

**Comment by kcarcia** [comment]
@jaypoulz Thank you!

**Pull request merged**
