### PR TITLE
Remove white bars of sides of featured vis

### PR DESCRIPTION
**Pull request by theyoyojo**
Added the id of #featured_vis to the div containing the content of the featured visualization

Added css in application.css.scss to define padding: 0 for the id

### CODE REVIEW

**Comment by theyoyojo** [comment]
added a 10px border radius to the iframe. It's kind of a hack, but it looks good,

**Comment by doug-salvati** [comment]
@theyoyojo - Your Pull Request contains some "files changed" which are associated with other issues.  You should merge with master to get that to go away.
```
git fetch upstream
git checkout JS-2706
git merge upstream/master
git push origin JS-2706
```

**Comment by theyoyojo** [comment]
I attempted the fix as per your recommendations. How does it look?

**Comment by doug-salvati** [comment]
for #2706

**Pull request merged**
