### PR TITLE
Quick fix for timestamp field matching

### PR DESCRIPTION
**Pull request by asalani93**
Address #2005.

This is just a quick band-aid for supporting multiple timestamp formats.

### CODE REVIEW

**Comment by jdalphon** [comment]
@asalani93 As long as this actually is just a band-aid and does not stay around long.

**Comment by asalani93** [comment]
It'll get fixed in the eventual future, but not right now.  Too many features that are actually important and have higher beneficiality:code ratios.  Will be done soon though.

**Comment by jdalphon** [comment]
@asalani93 Did you test to make sure both get uploaded correctly?

**Comment by asalani93** [comment]
yes

**Comment by jdalphon** [comment]
This will accept
01/02/2015 to mean Febuary 1st or January 2nd which is why we had one
STRICT date format. Which is why we should
have a format picker sooner rather then later on file upload.

On Mon, May 18, 2015 at 2:16 PM, Anthony Salani <notifications@github.com>
wrote:

> yes
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/isenseDev/rSENSE/pull/2138#issuecomment-103154899>.
>



-- 
--------------------------------
James Dalphond
UML Computer Science
Engaging Computing Group

**Pull request merged**
