### PR TITLE
API error messages are now more consistent.

### PR DESCRIPTION
**Pull request by bdonald25**
#1617
@jaypoulz
I will send an email before this is pulled.

### CODE REVIEW

**Comment by jaypoulz** [comment]
Assign to Kate Carcia when ready to be pulled

**Comment by kcarcia** [comment]
@bdonald25 Is this ready to be pulled yet?

**Comment by bdonald25** [comment]
@kcarcia Not yet, sorry. I need to send out an email first to warn people that it might affect their apps. I will send one out later today.

**Comment by bdonald25** [comment]
@kcarcia If this is pulled when would it go live? Next Friday?

**Comment by stowellm** [comment]
@bdonald25 How in particular will this affect apps?  If you explain this in the email then just ignore this comment.

**Comment by kcarcia** [comment]
@bdonald25 Next release is next Friday (February 13th)

**Comment by bdonald25** [comment]
@stowellm If you are parsing the server response of failed api calls for the tag "msg", after this pull request goes through that will fail. You will have to parse for the tag "error" instead. 

I am not sure if iOS even displays the server message to the user so you might be fine.
Android will be fine because all of the api calls check for both tags.

**Comment by bdonald25** [comment]
@kcarcia I made changes based upon Jim's feedback. It is ready to be pulled whenever you review it.

**Comment by bdonald25** [comment]
@jdalphon

**Pull request merged**
