### PR TITLE
Better API documentation

### PR DESCRIPTION
**Pull request by bdonald25**
#2006 #1987
@jaypoulz This is not ready to pull until I get some examples for the media object api calls. However, it would be great to get some feedback on the rest of the page.

### CODE REVIEW

**Comment by jaypoulz** [comment]
Here is my feedback:

- [ ] you know that build failing image at the top of the page? Trying changing it's source to:
``src="https://travis-ci.org/isenseDev/rSENSE.svg?branch=<%= @version %>"``
This will be a broken link for your local host and rsense-dev, but should check against the latest stable build in live, reducing the odds that you'll see "build failing" on the page.
- [ ] "Ok" should either by "OK" or "okay". I prefer the former.
- [ ] Whenever you list an object (link in an ajax call) in the documentation, line up the colons
- [ ] You know how you have XX to represent a variable in the doc line? Why not use that same variable in the code to represent what is missing. You can leave it bold, but using the same variable name would give a sense of internal consistentency
- [ ] The get projects docs are all kinds of wrong
- [ ] It's not obvious how to expand the docs (I mean, who reads directions!). It might be cool if they simply expanded on hover over, or maybe if there was a highlight effect on hover. Maybe the whole header part should be clickable instead of just the request type.

**Comment by kcarcia** [comment]
@bdonald25 It looks like you are ready for review again since you added that tag so I reassigned @jaypoulz

**Comment by jaypoulz** [comment]
I made a pull request to your branch, if that merges and passes testing, it'll be done.

**Comment by jaypoulz** [comment]
CAUTION: DO NOT PULL UNTIL #2077 HAS LANDED

**Pull request merged**
