### PR TITLE
Fix broken projects

### PR DESCRIPTION
**Pull request by bdonald25**
#2231 Some projects are broken because the User that created the project has been deleted but their projects are still on iSENSE. This is probably a symptom of us hiding projects instead of deleting them.

Example
http://isenseproject.org/projects/500
http://isenseproject.org/api/v1/projects/500

The project page will not display the user that created the project instead of crashing.
The api call will give null as the user instead of breaking.

### CODE REVIEW

**Comment by tylerpuleo** [comment]
Code looks good and it passes all the auto tests, but it didn't work when I tested it locally.

Here's my steps:

1. Make a new local branch
2. Fetch and merge Bobby's api500 branch
3. start server
4. Create a new user and a new project by this user
5. Use admin account to delete user
6. Go back to project/theID#
7. I didn't get beaker man I got this:

selection_003

**Comment by bdonald25** [comment]
That is correct behavior. That is telling you it cannot find the project which is correct because it was deleted when the user was. You get that screen because when you run isense locally it runs in debug mode. On live or dev you would get a 404.

There are some projects that exist, but the user that created them do not because we used to hide projects instead of deleting them. This fixes it so those hidden projects can still be viewed rather than a 500 error. If your db is a clone of live go to localhost:3000/projects/500.

**Comment by tylerpuleo** [comment]
I miss understood what the bug was. Good to go.

**Comment by bdonald25** [comment]
Testers: This fixes some projects such as isenseproject.org/projects/500 that gave the beaker man because the user who created the project was deleted.

If this project works on dev then the issue was fixed. rsense-dev.cs.uml.edu/projects/500

**Pull request merged**
