### PR TITLE
Deleting projects actually deletes projects

### PR DESCRIPTION
**Pull request by stowellm**
And you can delete a project with no title :cake: 
Addresses #1890

### CODE REVIEW

**Comment by asalani93** [comment]
Test

**Comment by stowellm** [comment]
DO NOT PULL YET:
To fix:
- [ ] For saved vises: in addition to checking if project is nil, check if project just doesn't exist, then set the label to "Project: deleted" (as does currently)
- [ ] Find out why on dev the "Delete X" button won't appear for a project with data sets but on my localhost it does

**Comment by stowellm** [comment]
I broke something again :( hold up.

**Comment by stowellm** [comment]
@jaypoulz We've been pulling things despite not currently having an HTML validator.  Is this good to pull as well?

**Comment by jaypoulz** [comment]
Not yet, I still have to test it manually

**Comment by stowellm** [comment]
How's that testing going :smile:

**Comment by jaypoulz** [comment]
Nice patch!

**Comment by kcarcia** [comment]
@stowellm does this also address #1773?

**Comment by stowellm** [comment]
@kcarcia No, this patch is strictly for deleting projects.  I've left the "deletion" (AKA hiding) of users/vis/etc alone.  I think that if we want to delete everything instead of hide everything, we should create a separate issue and patch for that purpose, especially since deleting things is bound to break a lot of tests.

**Comment by kcarcia** [comment]
@stowellm derp derp derp. I missed that one major detail. Sorry about that!

**Pull request merged**
