### PR TITLE
When you hit delete, it actually deletes

### PR DESCRIPTION
**Pull request by stowellm**
Addresses #1794 and any other issue we have regarding deleting things.

@jdalphon, @jaypoulz, and @kcarcia - No idea who may be interested in this pull request, but review/test at your leisure.  There is no more "hiding" things when we delete them.  They actually get deleted.

### CODE REVIEW

**Comment by kcarcia** [comment]
@stowellm How does this work? Does a deleted user's everything really go away?

**Comment by stowellm** [comment]
@kcarcia and I talked about this in person, but I'll summarize the discussion:

Deleting a user deletes everything in order of importance, e.g. news/likes/tutorials get deleted first.  Data sets are wiped second to last, and finally projects.  When attempting to delete a project, the code will check if any data sets still exist (recall this user's data sets have already been deleted, so a project created by this user with only his/her data sets previously now has none).  If data sets exist, the project ownership is changed to admin. Otherwise it is deleted.

**Comment by stowellm** [comment]
@jdalphon Do you mind reviewing this to make sure it's sensible for what you believe should happen?

**Comment by stowellm** [comment]
Bump.

**Comment by stowellm** [comment]
speed_bump_graphic

**Comment by jdalphon** [comment]
@stowellm Sorry, I was not getting emails about this issue for some reason. 

Yes, this looks sane for now. There are some other implications that we may need to deal with later. We may want to look into how other services like google docs, dropbox, and others deal with deleting shared content that has edits by other people. 

I'm still not convinced that deleting stuff out from under users without at least notifying them is a good idea. 

What is the current behavior for deleting a project outright?

**Comment by stowellm** [comment]
Currently on dev:
You can't delete a project with data sets.  Deleting a user that owns a project with data sets, however, just hides the project.  You can only visit it by direct URL.  The user will still be the "deleted" user since only the user's email gets changed.

In this pull request:
You still can't delete a project with data sets by default.  If you delete a user, all of his/her data sets are deleted first.  If it is found that now his/her project can be deleted (i.e. only that user contributed to it), it gets deleted.  Otherwise, since that project has contributions from other users, ownership switches to admin.  Then the user gets deleted.  We should note only admins can delete users though.

Another note:
As it stands, a project owner can already delete everyone else's data sets without warning, then delete his/her own project.

**Comment by jdalphon** [comment]
@stowellm That last part is what I was worried about. But if the owner can delete peoples stuff at any time, then is this just a moot point? 

I would say your PR as right now is fine, but we may change our minds in the next big meeting and say project owners are god and can delete their stuff. We will see after the meeting

**Comment by stowellm** [comment]
Sounds good - @kcarcia, ready for you to pull.

**Comment by kcarcia** [comment]
@stowellm I will pull this tomorrow after testing is complete. :)

**Pull request merged**
