### PR TITLE
Fix spelling mistakes and overflow.

### PR DESCRIPTION
**Pull request by bdonald25**
#2085

### CODE REVIEW

**Comment by kcarcia** [comment]
@bdonald25 Code looks fine to me.

@stowellm can you test this locally tomorrow morning, please?

**Comment by stowellm** [comment]
Found a couple issues.

1) There's a scrollbar for the "API Documentation" and "Build" titlebar thing:
why1

And you can scroll it up...? Now it goes away.
why2

----

2) Why is there only a highlight around the bottom, left, and right edges?
why3

**Comment by jaypoulz** [comment]
This passes the test part of the review, but for the stylistic part, could you please refactor the CSS file so that all of the `{` are on the same line as the block that opens it? In other words, the thing you added is fine of the rest of the file is wonk imho.

**Comment by jaypoulz** [comment]
@kcarcia I've marked this as both because it's ready to pull post microfixes

**Comment by bdonald25** [comment]
Sure thing.

**Comment by kcarcia** [comment]
@jaypoulz Sounds good! @bdonald25 please just tag me on this when you've made these fixes please :shipit:

**Comment by bdonald25** [comment]
@kcarcia should be all set now once it passes travis.

**Comment by kcarcia** [comment]
@bdonald25 Thank you!

**Pull request merged**
