### PR TITLE
Resized key image

### PR DESCRIPTION
**Pull request by kcarcia**
Do you think it looks better?

Addresses #2045

### CODE REVIEW

**Comment by stowellm** [comment]
That does look much better; no more squished key!  

Something else that I did notice when entering a key to contribute to a project is that the "Submit Key" button and "Key" text field have no layout margin between them (i.e. they're too close together); do you agree?

button_too_close

**Comment by kcarcia** [comment]
@stowellm 100% I'll modify the bug and fix that tomorrow. :)

**Comment by kcarcia** [comment]
@stowellm Fixed that, Mike. It's ready for review again.

**Comment by stowellm** [comment]
@kcarcia Looks great!  Passes my review.

**Pull request merged**
