### PR TITLE
Getting rid of useless ajax that only admins see. #2083 #2084

### PR DESCRIPTION
**Pull request by jdalphon**
We currently use crappy ajax to publish and unpublish news/tutorials causing: 
#2083 
#2084

Now it is simply a form with a hidden field set to be the opposite of the current hidden state.

Also tutorials were broken in that admins couldn't even see hidden ones. So that is fixed and the tests are better for it.

### CODE REVIEW

**Comment by kcarcia** [comment]
@jdalphon code looks fine to me. Will test locally tomorrow morning.

**Comment by kcarcia** [comment]
Those pages could probably use a little UI love, but since they are really admin only, that's low priority. Looks good to me.

**Comment by jaypoulz** [comment]
@jdalphon I think maybe some of this ajax was preventing XSS attacks on news and tutorials. Salani was breaking dev by injecting scripts into news article titles then publishing them to the homepage. Do you mind adding the rails sanitization call to that presave? Should be a few lines, but you know it best

**Comment by jdalphon** [comment]
@jaypoulz There was no ajax on either of those pages that did anything but handlebars for changing the hidden property of the element. Please open a new issue to fix this bug. 

It would be pretty low priority as we would not be injecting scripts into our own website. You need to be admin to create/edit tutorials or news.

**Pull request merged**
