### PR TITLE
Makes maps with one data point take on a default zoom level of 200km.

### PR DESCRIPTION
**Pull request by doug-salvati**
#2373

### CODE REVIEW

**Comment by tylerpuleo** [comment]
Fetch and merge upstream. Bobby made a fix that fixes circle.

**Comment by tylerpuleo** [comment]
its good once you fetch and merge

**Comment by doug-salvati** [comment]
I don't understand; how will fetching and merging on my machine affect this pull request?  Is it a different fetch/merge command than I use on a day-to-day basis?

**Comment by bdonald25** [comment]
Fetch from upstream and merge locally. Then push the changes to your
origin. Any changes you push to a branch on origin that you have an open
pull request for will also be included in the pull request automatically so
you don't need to close it and reopen it.

**Pull request merged**
