### PR TITLE
Add owner and key to data set hash

### PR DESCRIPTION
**Pull request by bdonald25**
@jaypoulz 
I'm not sure if there is a bug made for this. I can't find it if there is.

### CODE REVIEW

**Comment by jaypoulz** [comment]
I made you issue #2018. Would you mind labeling them as:
```
ownerId
ownerName
contribKey
```

Otherwise it looks good

**Comment by bdonald25** [comment]
@jaypoulz

**Comment by jdalphon** [comment]
@bdonald25 Documentation for the API?

**Comment by bdonald25** [comment]
@jdalphon There currently isn't any documentation for a get call on a data set. I'll add some documentation for it on my other branch that has all the changes I have been making to the docs.

**Comment by jaypoulz** [comment]
Passes my review!

**Pull request merged**
