### PR TITLE
Timeline vis now correctly disabled when there are not enough rows with timestamp data

### PR DESCRIPTION
**Pull request by pat-son**
#2295
Virtually identical bug to the map vis issue, so fixing it was a breeze. Added tests.

### CODE REVIEW

**Comment by bdonald25** [comment]
Fails Rubocop

**Comment by pat-son** [comment]
Should pass rubocop now

**Comment by bdonald25** [comment]
Failed test_contributions and test_delete_then_feature_visualization_mo

**Comment by pat-son** [comment]
Closed because [another request](https://github.com/isenseDev/rSENSE/pull/2357) includes these fixes.

**Pull request closed without merging**
