### PR TITLE
New Contact Page

### PR DESCRIPTION
**Pull request by stowellm**
Addresses #1659 

Go ahead and read the HTML if you really want to.  But here's some screenshots to check out.

---

1/3

contact1

---

2/3

contact2

---

3/3

contact3

### CODE REVIEW

**Comment by JKinsman** [comment]
@stowellm this passes my review.  Everything looks good! :smile:

**Comment by jaypoulz** [comment]
Wait for Skittles

**Comment by stowellm** [comment]
@jaypoulz  - should we pull this now rather than wait?  If the people we contacted truly wanted to be on the page, they would have responded. At what point are we more or less forcing them onto the page because we want them there as opposed to them willingly being there?

**Comment by kcarcia** [comment]
@stowellm do we assert the HTML is valid on this page? If so, please mark as reviewed. Otherwise, are you able to add a test that does so please?

**Comment by stowellm** [comment]
@kcarcia Yes, the contact page HTML is checked.

`home_controller_test.rb` lines 16-20:
```
  test 'should get contact' do
    get :contact
    assert_response :success
    assert_valid_html response.body
  end
```

Going to merge with upstream and mark as reviewed as requested.

**Pull request merged**
