### PR TITLE
Fixed check-all bug in table for visible fields

### PR DESCRIPTION
**Pull request by stowellm**
Addresses #1980 

The problems were:
- the code was checking the length of all fields versus selected fields instead of very simply checking if the "#Check All" box was selected or not, leading to the error described in the issue
- yFields was improperly being modified in the click event of the "#Check All" box - switched it to a temp variable called selFields

Additionally:
- Changed some "($ " to "$("
- Changed the name of the box to "#Check All" instead of "#Select All" to be consistent with the groups check-all box

### CODE REVIEW

**Comment by jaypoulz** [comment]
Why indeterminate? Is this style used somewhere else in the site?

**Comment by stowellm** [comment]
Indeterminate because I copy/pasted this code from baseVis.  Yes, its used elsewhere.

**Comment by jaypoulz** [comment]
Ahh ok. Well for grouping, it's different -> the grouping controls have a hierarchical structure to them. These do not. so we're in the clear.

Please no indeterminate here.

**Comment by stowellm** [comment]
You got it, doc! :rabbit: :tomato: (<-- please settle the tomato - there are no carrots)

**Comment by jaypoulz** [comment]
GG good to pull

**Pull request merged**
